services:

  postgres:
    image: postgres:16

    container_name: triad-postgres

    environment:
      POSTGRES_DB: Triad
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123@

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .

    container_name: triad-api

    depends_on:
      - postgres

    environment:
      ConnectionStrings__POSTGRES: Host=postgres;Port=5432;Database=Triad;Username=postgres;Password=123@

    ports:
      - "8080:8080"

volumes:
  postgres_data: