// <auto-generated />
using System;
using Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260708163108_EstruturaInicialSistema")]
    partial class EstruturaInicialSistema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Cardapio", b =>
                {
                    b.Property<int>("Id_Cardapio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Cardapio");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Cardapio"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nome");

                    b.HasKey("Id_Cardapio");

                    b.ToTable("cardapio", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Comanda", b =>
                {
                    b.Property<int>("Id_Comanda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Comanda");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Comanda"));

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("timestamptz")
                        .HasColumnName("DataAbertura");

                    b.Property<DateTime?>("DataFechamento")
                        .HasColumnType("timestamptz")
                        .HasColumnName("DataFechamento");

                    b.Property<int>("MesaId")
                        .HasColumnType("integer");

                    b.Property<int>("StatusComanda")
                        .HasColumnType("integer")
                        .HasColumnName("StatusComanda");

                    b.HasKey("Id_Comanda");

                    b.HasIndex("MesaId");

                    b.ToTable("comanda", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ItemCardapio", b =>
                {
                    b.Property<int>("Id_ItemCardapio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_ItemCardapio");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_ItemCardapio"));

                    b.Property<int>("CardapioId")
                        .HasColumnType("integer");

                    b.Property<int>("Categoria")
                        .HasColumnType("integer")
                        .HasColumnName("Categoria");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Descricao");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("boolean")
                        .HasColumnName("Disponivel");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nome");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("Preco");

                    b.HasKey("Id_ItemCardapio");

                    b.HasIndex("CardapioId");

                    b.ToTable("item_cardapio", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ItemPedido", b =>
                {
                    b.Property<int>("Id_ItemPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_ItemPedido");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_ItemPedido"));

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamptz")
                        .HasColumnName("DataAtualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamptz")
                        .HasColumnName("DataCriacao");

                    b.Property<int>("ItemCardapioId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nome");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("Observacao");

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("Quantidade");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("Status");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("ValorUnitario");

                    b.HasKey("Id_ItemPedido");

                    b.HasIndex("ItemCardapioId");

                    b.HasIndex("PedidoId");

                    b.ToTable("ItemPedidos");
                });

            modelBuilder.Entity("Domain.Entities.Mesa", b =>
                {
                    b.Property<int>("Id_Mesa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Mesa");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Mesa"));

                    b.Property<int>("NumeroMesa")
                        .HasColumnType("integer")
                        .HasColumnName("NumeroMesa");

                    b.Property<int>("StatusMesa")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id_Mesa");

                    b.ToTable("mesa", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Pedido", b =>
                {
                    b.Property<int>("Id_Pedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Pedido");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Pedido"));

                    b.Property<int>("ComandaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamptz")
                        .HasColumnName("DataCriacao");

                    b.Property<int>("MesaId")
                        .HasColumnType("integer");

                    b.Property<int>("SetorProducaoId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id_Pedido");

                    b.HasIndex("ComandaId");

                    b.HasIndex("MesaId");

                    b.HasIndex("SetorProducaoId");

                    b.ToTable("pedido", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.SetorProducao", b =>
                {
                    b.Property<int>("Id_SetorProducao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_SetorProducao");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_SetorProducao"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("Ativo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nome");

                    b.HasKey("Id_SetorProducao");

                    b.ToTable("setorProducao", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Comanda", b =>
                {
                    b.HasOne("Domain.Entities.Mesa", "Mesa")
                        .WithMany("Comandas")
                        .HasForeignKey("MesaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mesa");
                });

            modelBuilder.Entity("Domain.Entities.ItemCardapio", b =>
                {
                    b.HasOne("Domain.Entities.Cardapio", "Cardapio")
                        .WithMany("Itens")
                        .HasForeignKey("CardapioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cardapio");
                });

            modelBuilder.Entity("Domain.Entities.ItemPedido", b =>
                {
                    b.HasOne("Domain.Entities.ItemCardapio", "ItemCardapio")
                        .WithMany()
                        .HasForeignKey("ItemCardapioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Pedido", "Pedido")
                        .WithMany("ListaItemPedidos")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemCardapio");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Domain.Entities.Pedido", b =>
                {
                    b.HasOne("Domain.Entities.Comanda", "Comanda")
                        .WithMany("ListaPedidos")
                        .HasForeignKey("ComandaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Mesa", "Mesa")
                        .WithMany()
                        .HasForeignKey("MesaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.SetorProducao", "SetorProducao")
                        .WithMany("Pedidos")
                        .HasForeignKey("SetorProducaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comanda");

                    b.Navigation("Mesa");

                    b.Navigation("SetorProducao");
                });

            modelBuilder.Entity("Domain.Entities.Cardapio", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Domain.Entities.Comanda", b =>
                {
                    b.Navigation("ListaPedidos");
                });

            modelBuilder.Entity("Domain.Entities.Mesa", b =>
                {
                    b.Navigation("Comandas");
                });

            modelBuilder.Entity("Domain.Entities.Pedido", b =>
                {
                    b.Navigation("ListaItemPedidos");
                });

            modelBuilder.Entity("Domain.Entities.SetorProducao", b =>
                {
                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
